apiVersion: apps/v1
kind: Deployment
metadata:
  name: randomstring
  namespace: randomstring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stocks
  template:
    metadata:
      labels:
        app: stocks
    spec:
      containers:
      - name: goapp
        image: 654654309397.dkr.ecr.us-east-1.amazonaws.com/randomstring:latest
        ports:
        - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: service
  namespace: randomstring
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
spec:
  selector:
    app: stocks
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer
